all:
	@#gcc -Wall -g -std=c11 01test_fgetc_fputc.c -o 01test_fgetc_fputc.out
	@#gcc -Wall -g -std=c11 02test_fgetc.c -o 02test_fgetc.out
	@#gcc -Wall -g -std=c11 03test_fgets_fputs.c -o 03test_fgets_fputs.out
	gcc -Wall -g -std=c11 04test_fread_fwrite.c -o 04test_fread_fwrite.out
	
	
clean:
	rm *.out *.del