all:
	@#gcc -Wall -g -std=c11 01test_random.c -o 01test_random.out
	@#gcc -Wall -g -std=c11 02test_fgets.c -o 02test_fgets.out
	@#gcc -Wall -g -std=c11 03test_strncpy.c -o 03test_strncpy.out
	@#gcc -Wall -g -std=c11 04test_strcmp.c -o 04test_strcmp.out
	@#gcc -Wall -g -std=c11 05test_sscanf.c -o 05test_sscanf.out
	gcc -Wall -g -std=c11 06test_strtoken.c -o 06test_strtoken.out
	
clean:
	rm *.out