all:
	@#gcc -Wall -g -std=c11 01test_client.c -o 01test_client.out
	@#gcc -Wall -g -std=c11 01test_server.c -o 01test_server.out

	gcc -Wall -g -std=c11 02test_client.c -o 02test_client.out
	gcc -Wall -g -std=c11 02test_server.c -o 02test_server.out

clean:
	rm *.out