all:
	@#gcc -Wall -g -std=c11 01test_copy.c -o 01test_copy.out
	@#gcc -Wall -g -std=c11 02test_write.c -o 02test_write.out
	@#gcc -Wall -g -std=c11 03test_select.c -o 03test_select.out
	@#gcc -Wall -g -std=c11 04test_poll.c -o 04test_poll.out
	gcc -Wall -g -std=c11 05test_epoll.c -o 05test_epoll.out
	
clean:
	rm *.out