all:
	@#gcc -Wall -g -std=c11 01easy.c -o 01easy.out -I/usr/local/curl -lcurl
	@#g++ -Wall -g -std=c++17 02writefunction.cpp -o 02writefunction.out -I/usr/local/curl -lcurl
	g++ -Wall -g -std=c++17 03multi.cpp -o 03multi.out -I/usr/local/curl -lcurl
clean:
	rm *.out