all:
	@#gcc -Wall -g -std=c11 01test_pwd.c -o 01test_pwd.out -D_XOPEN_SOURCE -lcrypt
	@#gcc -Wall -g -std=c11 02test_time.c -o 02test_time.out
	gcc -Wall -g -std=c11 03test_userid_name.c -o 03test_userid_name.out
clean:
	rm *.out